apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-iugf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uvta-tenant/rhtap-demo-app/hacbs-test-project-iugf@sha256:7881a8d10ff184a655b0845e33afcc15c54729293012523cdb146ea62a5c8657
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
